kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: file-service
  name: file-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: <your registry>/file-service:11
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          command:
            - java 
          args:
            - -jar
            - /FileService-1.0-SNAPSHOT.jar

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: file-service
  name: file-service-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    app: file-service
    
